=== brienen/ddas-app/src/json_schema_Uitwisselmodel_VS.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/VNG-Realisatie/ddas/refs/heads/Vroegsignalering/vroegsignalering/v0.1/json_schema_Uitwisselmodel.json",
    "title": "Uitwisselmodel",
    "type": "object",
    "description": "Het uitwisselmodel is een model dat de gegevens bevat die uitgewisseld worden tussen de verschillende partijen.",
    "properties": {
        "startdatumLevering": {
            "description": "De begindatum van de periode waarover gerapporteerd wordt binnen de levering",
            "$ref": "#/$defs/datum"
        },
        "einddatumLevering": {
            "description": "De einddatum van de periode waarover gerapporteerd wordt binnen de levering",
            "$ref": "#/$defs/datum"
        },
        "aanleverdatumEnTijd": {
            "description": "De datum en tijd waarop de gegevens zijn aangeleverd.",
            "$ref": "#/$defs/datum-tijd"
        },
        "codeGegevensleverancier": {
            "description": "Code van de gegevensleverancier (softwareleverancier of hosting partij) die de gegevens voor 1 of meer partijen levert.",
            "type": "string"
        },
        "leveringen": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "description": "Een levering is steeds een schuldhulporganisatie met daarbij een verzameling van vroegsignalen die op een bepaald moment worden aangeleverd.",
                "properties": {
                    "teller": {
                        "description": "Teller van het aantal leveringen dat in het bestand is opgenomen.",
                        "type": "integer"
                    },
                    "aanleverende_organisatie": {
                        "type": "object",
                        "description": "Een schuldhulporganisatie is een instantie die individuen en gezinnen helpt met het beheren, verminderen en oplossen van hun schulden door middel van advies, begeleiding en bemiddeling.\nHet betreft een gemeenten of een SHV-organisatie die de gemeentelijke schuldhulpverleningstaak vanuit een gemeente gemandateerd of gedelegeerd heeft. \n",
                        "properties": {
                            "(Statutaire) Naam": {
                                "description": "Naam van de niet-natuurlijke persoon zoals deze is vastgelegd in de statuten (rechtspersoon) of in de vennootschapsovereenkomst is overeengekomen (Vennootschap onder firma of Commanditaire vennootschap).",
                                "type": "string"
                            },
                            "KvK-nummer": {
                                "description": "Landelijk uniek identificerend administratienummer van een MAATSCHAPPELIJKE ACTIVITEIT behorend bij een SUBJECT zoals toegewezen door de Kamer van Koophandel (KvK).",
                                "type": "string"
                            },
                            "postcode": {
                                "type": "string"
                            },
                            "gemeentecode": {
                                "description": "De gemeentecode als de aanleverende organisatie een gemeente is. Raadpleeg de lijst met gemeentecodes via: https://www.cbs.nl/nl-nl/onze-diensten/open-data/statline-als-open-data/gemeentelijke-indeling-op-1-januari-2024",
                                "type": "string"
                            },
                            "contactpersonen": {
                                "type": "array",
                                "minItems": 1,
                                "items": {
                                    "type": "object",
                                    "description": "Contactpersoon van de organisatie waarvan de gegevens worden aangeleverd.",
                                    "properties": {
                                        "naam": {
                                            "type": "string"
                                        },
                                        "functietitel": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "$ref": "#/$defs/email"
                                        },
                                        "telefoonnummer": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
              "vroegsignalen": {
                  "type": "array",
                  "items": {
                      "type": "object",
                      "description": "Een Vroegsignaal is een bericht dat door een signaalpartner (zoals een zorgverzekeraar, energieleverancier of verhuurder) aan de gemeente wordt verstrekt, met als doel de gemeente te informeren over een mogelijk beginnende schuldsituatie van een inwoner. Het vroegsignaal vormt het startpunt van het gemeentelijk proces van vroegsignalering van schulden.\n\nDe juridische grondslag voor het ontvangen en verwerken van vroegsignalen is vastgelegd in artikel 2.2.1 van de Wet gemeentelijke schuldhulpverlening (Wgs). Deze wet verplicht gemeenten om vroegtijdig signalen van betalingsachterstanden te ontvangen en op basis daarvan inwoners passende hulp aan te bieden.\n",
                      "properties": {
                          "ID": {
                              "type": "string"
                          },
                          "crisissignaal": {
                              "description": "Betreft het een crisis?\n",
                              "type": "boolean"
                          },
                          "warmeOverdracht": {
                              "description": "Er is al contact met persoon. Betreft verzoek deze persoon op te pakken in het kader van vroegsignalering. ",
                              "type": "boolean"
                          },
                          "bedrag": {
                              "$ref": "#/$defs/bedrag"
                          },
                          "ontstaansdatum": {
                              "$ref": "#/$defs/datum"
                          },
                          "signaaldatum": {
                              "description": "Datum waarop de signaalpartner het signaal heeft verstuurd.",
                              "$ref": "#/$defs/datum"
                          },
                          "status": {
                              "$ref": "#/$defs/EnumSignaalstatus"
                          },
                          "signaalpartner": {
                              "type": "object",
                              "description": "Een signaalpartner is een organisatie die op grond van artikel 2.2.1 van de Wet gemeentelijke schuldhulpverlening (Wgs) bevoegd is om signalen van betalingsachterstanden door te geven aan de gemeente met het doel vroegtijdige hulpverlening bij schulden mogelijk te maken. Signaalpartners zijn dienstverleners met een maatschappelijk belang, zoals zorgverzekeraars, energieleveranciers, drinkwaterbedrijven en woningverhuurders.\n\nEen signaalpartner verstrekt een vroegsignaal aan de gemeente wanneer bij een klant of huurder sprake is van een betalingsachterstand die voldoet aan de wettelijke en/of contractuele criteria voor signalering.\n",
                              "properties": {
                                  "type": {
                                      "$ref": "#/$defs/EnumSignaalpartner"
                                  },
                                  "Organisatienaam": {
                                      "type": "string"
                                  }
                              }
                          },
                          "client": {
                              "type": "object",
                              "description": "Een ingeschreven persoon die gebruik maakt van producten en diensten van de gemeente.",
                              "properties": {
                                  "Burgerservicenummer": {
                                      "type": "string"
                                  },
                                  "Voorletters": {
                                      "type": "string"
                                  },
                                  "Achternaam": {
                                      "type": "string"
                                  },
                                  "Geboortedatum": {
                                      "description": "De datum waarop de ander natuurlijk persoon is geboren.",
                                      "$ref": "#/$defs/datum"
                                  },
                                  "Straatnaam": {
                                      "type": "string"
                                  },
                                  "Postcode": {
                                      "type": "string"
                                  },
                                  "Huisnummer": {
                                      "type": "string"
                                  },
                                  "Huisnummertoevoeging": {
                                      "type": "string"
                                  },
                                  "Plaatsnaam": {
                                      "type": "string"
                                  }
                              }
                          }
                      },
                      "required": [
                          "ID",
                          "client",
                          "signaalpartner"
                      ],
                      "additionalProperties": false
                  }
              },
              "vroegsignaalzaken": {
                  "type": "array",
                  "items": {
                      "type": "object",
                      "description": "Een Vroegsignaalzaak is procesmatige eenheid binnen de gemeentelijke organisatie waarin de behandeling van &#233;&#233;n of meerdere vroegsigna(a)len is/zijn ondergebracht. De vroegsignaalzaak omvat alle handelingen die de gemeente verricht naar aanleiding van het ontvangen vroegsignaal, zoals het vastleggen van het signaal, het uitvoeren van een eerste beoordeling, het leggen van contact met de inwoner, het registreren van contactpogingen en -resultaten, en het eventueel toeleiden naar schuldhulpverlening of andere passende ondersteuning.",
                      "properties": {
                          "resultaat": {
                              "$ref": "#/$defs/EnumEindresultaat"
                          },
                          "matchingsdatum": {
                              "$ref": "#/$defs/datum"
                          },
                          "startdatum_matchtingperiode": {
                              "$ref": "#/$defs/datum"
                          },
                          "datum_opgepakt": {
                              "$ref": "#/$defs/datum"
                          },
                          "einddatum_matchingperiode": {
                              "$ref": "#/$defs/datum"
                          },
                          "gemeentecode": {
                              "description": "Code van de gemeente names wie de zaak is opgepakt.",
                              "type": "string"
                          },
                          "vroegsignalen": {
                              "type": "array",
                              "items": {
                                  "type": "object",
                                  "description": "Referentie naar het vroegsignaal dat hoort bij de vroegsignaalzaak. ",
                                  "properties": {
                                      "ID": {
                                          "type": "string"
                                      }
                                  },
                                  "required": [
                                      "ID"
                                  ],
                                  "additionalProperties": false
                              },
                              "minItems": 1,
                              "uniqueItems": true
                          },
                          "contactpogingen": {
                              "type": "array",
                              "items": {
                                  "type": "object",
                                  "description": "Een Contactpoging is de actie die de gemeente onderneemt om in contact te treden met de inwoner naar aanleiding van een vroegsignaal. Een contactpoging maakt onderdeel uit van de vroegsignaalzaak en kan verschillende vormen aannemen, zoals een telefoongesprek, huisbezoek, brief of digitaal bericht. Van elke contactpoging wordt vastgelegd wanneer deze is gedaan, op welke wijze, met welk doel en wat het resultaat was (bijvoorbeeld: geen gehoor, gesprek gevoerd, brief retour ontvangen).\n",
                                  "properties": {
                                      "soort": {
                                          "$ref": "#/$defs/EnumContactsoort"
                                      },
                                      "bereikt": {
                                          "description": "Er is succesvol contact met de client gemaakt.",
                                          "type": "boolean"
                                      },
                                      "datum": {
                                          "$ref": "#/$defs/datum"
                                      },
                                      "dagdeel": {
                                          "description": "Ochtend, middag of avond",
                                          "$ref": "#/$defs/EnumDagdeel"
                                      }
                                  }
                              }
                          }
                      },
                      "required": [
                          "gemeentecode"
                      ],
                      "additionalProperties": false
                  }
              }
            }
          }
        }
    },
    "required": [
        "codeGegevensleverancier",
        "aanleverdatumEnTijd",
        "einddatumLevering",
        "startdatumLevering"
    ],
    "additionalProperties": false,
    "$defs": {
        "datum": {
            "type": "string",
            "format": "date",
            "description": "Een datum in het formaat YYYY-MM-DD."
        },
        "email": {
            "type": "string",
            "format": "email",
            "description": "Een emailadres."
        },
        "tijd": {
            "type": "string",
            "format": "time",
            "description": "De tijd in het formaat HH:MM:SS (ISO 8601)."
        },
        "datum-tijd": {
            "type": "string",
            "format": "date-time",
            "description": "Datum en tijd in het formaat YYYY-MM-DDTHH:MM:SSZ (ISO 8601)."
        },
        "bedrag": {
            "type": "integer",
            "description": "Een geldbedrag in hele euros nauwkweurig."
        },
        "EnumContactsoort": {
            "type": "string",
            "description": "Enumeratie met daarin de soorten onderscheiden contactsoorten bij een contactpoging.",
            "enum": [
                "Mail",
                "Brief",
                "SMS/Whatsapp",
                "Telefoon",
                "Huisbezoek",
                "Kaartje",
                "Overige"
            ]
        },
        "EnumDagdeel": {
            "type": "string",
            "enum": [
                "Ochtend",
                "Middag",
                "Avond"
            ]
        },
        "EnumEindresultaat": {
            "type": "string",
            "description": "Enumeratie met de soorten Eindresultaten van een Vroegsignaalzaak.",
            "enum": [
                "Niet opgepakt: inwoner wil geen contact",
                "Niet opgepakt: geen capaciteit",
                "Niet opgepakt",
                "Inwoner al bekend bij schuldhulpverlening",
                "Geen contact (meer) kunnen krijgen",
                "Inwoner wil geen hulp",
                "Inwoner probeert het zelf op te lossen",
                "Inwoner heeft betaald/betalingsregeling getroffen voor oppakken melding",
                "Inwoner heeft zelf betaald/betalingsregeling getroffen na oppakken melding",
                "(Budget)advies en/of quick fix",
                "Inwoner al een ander lopend traject",
                "Verwijzing financieel",
                "Voorzien van informatie",
                "Niet opgepakt: BRP-uitsluiting",
                "Verwijzing niet-financieel",
                "Inwoner heeft al ander lopend traject"
            ]
        },
        "EnumSignaalpartner": {
            "type": "string",
            "description": "Enumeratie met de soorten te onderscheiden Signaalpartners.",
            "enum": [
                "Energie",
                "Huur",
                "Hypotheek",
                "CAK Zorgverzekeringen",
                "Zorg",
                "Water",
                "DUO",
                "Belastingdienst",
                "CAK Eigen bijdrage",
                "Overige",
                "Dienst Toeslagen"
            ]
        },
        "EnumSignaalstatus": {
            "type": "string",
            "enum": [
                "Nog niet opgepakt",
                "Onterecht signaal",
                "Overleden",
                "Woont niet in gemeente",
                "Herhaalde melding",
                "Niet opgepakt",
                "Opgepakt",
                "Woont op een ander adres binnen gemeente"
            ]
        }
    }
}

=== brienen/ddas-app/Archief/json_schema_Uitwisselmodel_data.json
{
  "leveringen": [
    {
      "teller": 1,
      "aanleverende_organisatie": {
        "(Statutaire) Naam": "Gemeente Heumen",
        "gemeentecode": "GM0252"
      },
      "schuldhulptrajecten": [
        {
          "gemeentecode": "GM0252"
        }
      ]
    }
  ],
  "startdatumLevering": "2024-01-01",
  "einddatumLevering": "2024-12-31",
  "aanleverdatumEnTijd": "2025-02-01T12:00:00.000+01:00",
  "codeGegevensleverancier": "Handmatige Levering"
}
